// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import ThemeProvider from "@/components/providers/ThemeProvider";
import LoadingScreen from "@/components/ui/LoadingScreen";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Ankur Chakraborty | Frontend Developer",
    template: "%s | Ankur Chakraborty",
  },

  description:
    "Frontend Developer specializing in React, Next.js, TypeScript and Tailwind CSS. Building modern, responsive and scalable web applications.",

  keywords: [
    "Ankur Chakraborty",
    "Frontend Developer",
    "React",
    "Next.js",
    "TypeScript",
    "Tailwind CSS",
    "Portfolio",
  ],

  authors: [
    {
      name: "Ankur Chakraborty",
    },
  ],

  creator: "Ankur Chakraborty",

  metadataBase: new URL("https://ankur-portfolio-five.vercel.app"),

  openGraph: {
    title: "Ankur Chakraborty | Frontend Developer",
    description:
      "Frontend Developer specializing in React, Next.js and TypeScript.",

    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body className="min-h-full bg-white text-gray-900 antialiased dark:bg-[#050816] dark:text-white">
        <ThemeProvider>
          <LoadingScreen />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}